### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zee1978** [NoisyLeon/pyaftan#3]
Dear author
I am facing the following problem. How to solve this issue.

Traceback (most recent call last):
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 128, in __getattr__
    return self.__getitem__(name, default)
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 74, in __getitem__
    return self.__dict__[name]
KeyError: 'dist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zafar/pyaftan-master/pyaftan.py", line 848, in aftan
    dist                    = self.stats.sac.dist
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 130, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: dist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 128, in __getattr__
    return self.__getitem__(name, default)
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 74, in __getitem__
    return self.__dict__[name]
KeyError: 'evla'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_aftan.py", line 14, in <module>
    atr1.aftan(tmin=5., tmax=20., vmin=2.5, vmax=3.5, phvelname='ak135.disp')
  File "/home/zafar/pyaftan-master/pyaftan.py", line 850, in aftan
    dist, az, baz           = obspy.geodetics.base.gps2dist_azimuth(self.stats.sac.evla, self.stats.sac.evlo,
  File "/home/zafar/anaconda3/lib/python3.7/site-packages/obspy/core/util/attribdict.py", line 130, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: evla

**Comment by NoisyLeon** [comment]
Please make sure you have evla, evlo, stla and stlo correctly stored in your SAC header attributes.

**Comment by zee1978** [comment]
Respected Professor
I have correctly added the information.
When I run, the problem is lag time. Can you please help me to resolve this
issue.

" Run C test:
pi/4= -1.0, vmin= 1.500000, vmax= 5.000000, tmin= 4.000000, tmax= 30.000000
Tresh= 20.000000, Filter factor= 1.000000, taperl= 1.000000, SNR= 0.200000,
Match = 1.000000
Data file name=ctest/COR_N.MSMH_N.TYNH.SAC
Phase velocity prediction file name= ctest/COR_N.MSMH_N.TYNH.SAC_PHP
Wrong SAC header n=71999 lag=-435163329
#filters= 64, Perc=  50.00 %, npoints= 5, t0= 435163329.35
FTAN - the first ineration
Segmentation fault (core dumped)
 Run gfortran test:
 pi/4= -1.0 vmin=  1.50 vmax=  5.00 tmin=   4.00 tmax=  30.00
 tresh=   20.00 filter factor=   1.00 taperl=   1.00 snr=    0.20 match =
 1.00
 Data file name= ftest/COR_N.MSMH_N.TYNH.SAC
 Phase velocity prediction file name= ftest/COR_N.MSMH_N.TYNH.SAC_PHP
Wrong SAC header n=71999 lag=3599
 t0 =   -3599.8999023437500
 #filters=    64 Perc=  50.00 npoints=     5
 FTAN - the first ineration\n
 Starting period=                   Infinity , Phase velocity=
      Infinity
 Starting period=                   Infinity , Phase velocity=
      Infinity
REESULT: O.K."

Waiting here for your kind advice.
Regards

**Comment by NoisyLeon** [comment]
Seems to me you are trying the pure fortran version. If you encounter any problem, you should contact the original author (Misha Barmin).
Also, after adding the header attributes, have you tried my python version?
